THRESHOLD = 5
MINIMAL_NUMBER_OF_OBSERVATIONS = 100
MIN_CLASS_NUMBER = 2 
EDA_NAME = "Data Analysis"
TFIDF_NAME = "Simple Classification Baseline"
RANDOM_STATE = 42
ANNOTATION_THRESHOLD = 0.9
BASE_CHECK_THRESHOLD = 90
